use_frameworks!

target 'ZeroUtilTest_Example' do
  pod 'ZeroUtilTest', :path => '../'

  target 'ZeroUtilTest_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
